// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "6QHTSK"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "https://mit-license.org/"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/chart-display": {
            "get": {
                "description": "获取谱面展示数据库的谱面",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chartDisplay"
                ],
                "summary": "获取谱面展示数据库的谱面",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码,默认1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页面限制，默认20",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "对应的谱面",
                        "schema": {
                            "$ref": "#/definitions/Controllers.ChartDisplayOutput"
                        }
                    }
                }
            }
        },
        "/chart-display/:chartID": {
            "get": {
                "description": "获取谱面展示数据库的指定ID的谱面",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chartDisplay"
                ],
                "summary": "获取谱面展示数据库的谱面",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "谱面ID",
                        "name": "chartID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "对应的谱面",
                        "schema": {
                            "$ref": "#/definitions/Controllers.ChartDisplayOutputID"
                        }
                    }
                }
            }
        },
        "/charter-like-rank": {
            "get": {
                "description": "获取谱师获赞数的排行",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BestdoriInfo"
                ],
                "summary": "获取谱师获赞数的排行",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码,默认1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页面限制，默认20",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "对应的谱面",
                        "schema": {
                            "$ref": "#/definitions/Controllers.InfoOutput"
                        }
                    }
                }
            }
        },
        "/charter-list": {
            "get": {
                "description": "获取所追踪的谱师列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BestdoriInfo"
                ],
                "summary": "获取所追踪的谱师列表",
                "responses": {
                    "200": {
                        "description": "谱师列表",
                        "schema": {
                            "$ref": "#/definitions/Controllers.InfoOutput"
                        }
                    }
                }
            }
        },
        "/charter-post-rank": {
            "get": {
                "description": "获取谱师发表谱面的排行",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BestdoriInfo"
                ],
                "summary": "获取谱师发表谱面的排行",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码,默认1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页面限制，默认20",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "对应的谱面",
                        "schema": {
                            "$ref": "#/definitions/Controllers.InfoOutput"
                        }
                    }
                }
            }
        },
        "/charter/:charter/basic-info": {
            "get": {
                "description": "获取谱师的基本信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BestdoriInfo"
                ],
                "summary": "获取谱师的基本信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "谱师用户名",
                        "name": "charter",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码,默认1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页面限制，默认20",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "谱师基础信息",
                        "schema": {
                            "$ref": "#/definitions/Controllers.InfoOutput"
                        }
                    }
                }
            }
        },
        "/charter/:charter/like-rank": {
            "get": {
                "description": "获取谱师发表的赞数排行",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BestdoriInfo"
                ],
                "summary": "获取谱师发表的赞数排行",
                "parameters": [
                    {
                        "type": "string",
                        "description": "谱师用户名",
                        "name": "charter",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码,默认1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页面限制，默认20",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "谱面列表",
                        "schema": {
                            "$ref": "#/definitions/Controllers.InfoOutput"
                        }
                    }
                }
            }
        },
        "/charter/:charter/note-rank": {
            "get": {
                "description": "获取谱师发表的音符数排行",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BestdoriInfo"
                ],
                "summary": "获取谱师发表的音符数排行",
                "parameters": [
                    {
                        "type": "string",
                        "description": "谱师用户名",
                        "name": "charter",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码,默认1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页面限制，默认20",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "谱面列表",
                        "schema": {
                            "$ref": "#/definitions/Controllers.InfoOutput"
                        }
                    }
                }
            }
        },
        "/charter/:charter/nps-rank": {
            "get": {
                "description": "获取谱师发表的谱面的NPS排行",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BestdoriInfo"
                ],
                "summary": "获取谱师发表的谱面的NPS排行",
                "parameters": [
                    {
                        "type": "string",
                        "description": "谱师用户名",
                        "name": "charter",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码,默认1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页面限制，默认20",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "谱面列表",
                        "schema": {
                            "$ref": "#/definitions/Controllers.InfoOutput"
                        }
                    }
                }
            }
        },
        "/charter/:charter/post": {
            "get": {
                "description": "获取谱师发表的谱面",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BestdoriInfo"
                ],
                "summary": "获取谱师发表的谱面",
                "parameters": [
                    {
                        "type": "string",
                        "description": "谱师用户名",
                        "name": "charter",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码,默认1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页面限制，默认20",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "谱面列表",
                        "schema": {
                            "$ref": "#/definitions/Controllers.InfoOutput"
                        }
                    }
                }
            }
        },
        "/charter/:charter/time-rank": {
            "get": {
                "description": "获取谱师发表的谱面的时间排行",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BestdoriInfo"
                ],
                "summary": "获取谱师发表的谱面的时间排行",
                "parameters": [
                    {
                        "type": "string",
                        "description": "谱师用户名",
                        "name": "charter",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码,默认1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页面限制，默认20",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "谱面列表",
                        "schema": {
                            "$ref": "#/definitions/Controllers.InfoOutput"
                        }
                    }
                }
            }
        },
        "/map-data": {
            "post": {
                "description": "根据用户上传的谱面获取指定格式谱面",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mapData"
                ],
                "summary": "从用户上传谱面获取谱面",
                "parameters": [
                    {
                        "description": "需转换的谱面",
                        "name": "map",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/utils.MapInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "对应的谱面",
                        "schema": {
                            "$ref": "#/definitions/utils.MapOutput"
                        }
                    }
                }
            }
        },
        "/map-data/bestdori/:chartID": {
            "get": {
                "description": "根据谱面ID、谱面难度从Bestdori获取谱面",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mapData"
                ],
                "summary": "从Bestdori获取谱面",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "谱面ID",
                        "name": "chartID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "谱面难度差分指定，默认Expert",
                        "name": "diff",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "输出谱面格式，默认BestdoriV2",
                        "name": "map_format_out",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "对应的谱面",
                        "schema": {
                            "$ref": "#/definitions/utils.MapOutput"
                        }
                    }
                }
            }
        },
        "/map-info": {
            "post": {
                "description": "根据用户上传的谱面获取指定格式谱面信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mapInfo"
                ],
                "summary": "从用户上传谱面获取谱面信息",
                "parameters": [
                    {
                        "description": "需转换的谱面",
                        "name": "map",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/utils.MapInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "对应的谱面",
                        "schema": {
                            "$ref": "#/definitions/Controllers.MapInfoOutput"
                        }
                    }
                }
            }
        },
        "/map-info/bestdori/:chartID": {
            "get": {
                "description": "根据谱面ID、谱面难度从Bestdori获取谱面并分析得到数据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mapInfo"
                ],
                "summary": "从Bestdori获取谱面并分析数据",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "谱面ID",
                        "name": "chartID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "谱面难度差分指定，默认Expert",
                        "name": "diff",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "输出谱面格式，默认BestdoriV2",
                        "name": "map_format_out",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "解析的谱面信息",
                        "schema": {
                            "$ref": "#/definitions/Controllers.MapInfoOutput"
                        }
                    }
                }
            }
        },
        "/song-like-rank": {
            "get": {
                "description": "获取谱面获赞数的排行",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BestdoriInfo"
                ],
                "summary": "获取谱面获赞数的排行",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码,默认1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页面限制，默认20",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "对应的谱面",
                        "schema": {
                            "$ref": "#/definitions/Controllers.InfoOutput"
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "description": "根据内部信息得到API的版本",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Version"
                ],
                "summary": "获得API版本",
                "responses": {
                    "200": {
                        "description": "获得的API版本号",
                        "schema": {
                            "$ref": "#/definitions/Models.APIVersion"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Controllers.ChartDisplayOutput": {
            "type": "object",
            "properties": {
                "chart_set": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/chartFormat.Chart"
                    }
                },
                "result": {
                    "type": "boolean"
                }
            }
        },
        "Controllers.ChartDisplayOutputID": {
            "type": "object",
            "properties": {
                "chart_set": {
                    "$ref": "#/definitions/chartFormat.Chart"
                },
                "result": {
                    "type": "boolean"
                }
            }
        },
        "Controllers.InfoOutput": {
            "type": "object",
            "properties": {
                "list": {},
                "result": {
                    "type": "boolean"
                }
            }
        },
        "Controllers.MapInfoOutput": {
            "type": "object",
            "properties": {
                "mapDifficultyExtend": {
                    "description": "MapDifficultyExtend"
                },
                "mapDifficultyStandard": {
                    "$ref": "#/definitions/Models.MapDifficultyStandard"
                },
                "mapInfoExtend": {
                    "description": "MapInfoExtend"
                },
                "mapInfoStandard": {
                    "$ref": "#/definitions/Models.MapInfoStandard"
                },
                "result": {
                    "type": "boolean"
                }
            }
        },
        "Models.APIVersion": {
            "type": "object",
            "properties": {
                "version": {
                    "type": "string"
                }
            }
        },
        "Models.Distribution": {
            "type": "object",
            "properties": {
                "hit": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "note": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                }
            }
        },
        "Models.MapDifficultyStandard": {
            "type": "object",
            "properties": {
                "blueWhiteDifficulty": {
                    "type": "number"
                },
                "difficulty": {
                    "type": "number"
                },
                "maxScreenNPS": {
                    "type": "number"
                },
                "totalHPS": {
                    "type": "number"
                },
                "totalNPS": {
                    "type": "number"
                }
            }
        },
        "Models.MapInfoStandard": {
            "type": "object",
            "properties": {
                "bpmhigh": {
                    "type": "number"
                },
                "bpmlow": {
                    "type": "number"
                },
                "distribution": {
                    "$ref": "#/definitions/Models.Distribution"
                },
                "irregular": {
                    "description": "存在多压/交叉（出张）0 失败 1 标准 2 非标准",
                    "type": "integer"
                },
                "irregularInfo": {
                    "description": "无法分析的第一个错误情况",
                    "type": "string"
                },
                "mainBPM": {
                    "type": "number"
                },
                "maxScreenNPS": {
                    "type": "number"
                },
                "noteCount": {
                    "$ref": "#/definitions/Models.NoteCount"
                },
                "totalHPS": {
                    "type": "number"
                },
                "totalHitNote": {
                    "type": "integer"
                },
                "totalNPS": {
                    "type": "number"
                },
                "totalNote": {
                    "type": "integer"
                },
                "totalTime": {
                    "type": "number"
                }
            }
        },
        "Models.NoteCount": {
            "type": "object",
            "properties": {
                "direction": {
                    "type": "object",
                    "properties": {
                        "left": {
                            "type": "integer"
                        },
                        "right": {
                            "type": "integer"
                        },
                        "total": {
                            "type": "integer"
                        }
                    }
                },
                "flick": {
                    "type": "integer"
                },
                "single": {
                    "type": "integer"
                },
                "slideEnd": {
                    "type": "integer"
                },
                "slideHidden": {
                    "type": "integer"
                },
                "slideStart": {
                    "type": "integer"
                },
                "slideTick": {
                    "type": "integer"
                },
                "sprhythm": {
                    "type": "boolean"
                }
            }
        },
        "chartFormat.Chart": {
            "type": "object",
            "properties": {
                "artists": {
                    "description": "谱面的艺术家",
                    "type": "string"
                },
                "author": {
                    "type": "object",
                    "properties": {
                        "authorID": {
                            "description": "谱面作者用户名",
                            "type": "integer"
                        },
                        "authorName": {
                            "description": "Author_Other 其他作者时使用的名义",
                            "type": "string"
                        }
                    }
                },
                "chartID": {
                    "description": "已提交：BanGround社区谱面ID,未提交：Bestdori社区Ex/SpID",
                    "type": "integer"
                },
                "diffs": {
                    "type": "object",
                    "properties": {
                        "bestdoriChartID": {
                            "description": "Bestdori的谱面ID 0 就是未发表",
                            "type": "integer"
                        },
                        "bpmhigh": {
                            "type": "number"
                        },
                        "bpmlow": {
                            "type": "number"
                        },
                        "diff": {
                            "type": "integer"
                        },
                        "irregular": {
                            "description": "存在多压/交叉（出张）0 失败 1 标准 2 非标准",
                            "type": "integer"
                        },
                        "irregularInfo": {
                            "description": "无法分析的第一个错误情况",
                            "type": "string"
                        },
                        "level": {
                            "type": "integer"
                        },
                        "mainBPM": {
                            "type": "number"
                        },
                        "totalNPS": {
                            "type": "number"
                        },
                        "totalNote": {
                            "type": "integer"
                        },
                        "totalTime": {
                            "type": "number"
                        }
                    }
                },
                "rel": {
                    "description": "访问网址",
                    "type": "string"
                },
                "songUrl": {
                    "description": "谱面资源",
                    "type": "object",
                    "properties": {
                        "audio": {
                            "type": "string"
                        },
                        "cover": {
                            "type": "string"
                        }
                    }
                },
                "submitted": {
                    "description": "是否已经提交到BanGround社区",
                    "type": "boolean"
                },
                "title": {
                    "description": "谱面的标题",
                    "type": "string"
                }
            }
        },
        "utils.MapInput": {
            "type": "object",
            "properties": {
                "Options": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "map": {},
                "map_format_in": {
                    "type": "string"
                }
            }
        },
        "utils.MapOutput": {
            "type": "object",
            "properties": {
                "map": {},
                "result": {
                    "type": "boolean"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "2.0",
	Host:        "127.0.0.1:8080",
	BasePath:    "/v2",
	Schemes:     []string{},
	Title:       "ayachan API",
	Description: "api 计算Bestdori谱面难度，获得Bestdori数据，常见Bandori谱面格式转换等",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
